### ISSUE TITLE
Provide up to date .deb packages

### ISSUE THREAD

**Issue by girst** [davidjb/pass-ios#11]
As someone without access to Xcode / a Mac I would really appreciate prebuilt packages. 
The one linked in the wiki does not seem to work or be up to date. 

Thanks a lot

**Comment by davidjb** [comment]
Give https://github.com/davidjb/pass-ios/releases/tag/v0.2.1 a shot and see how you go.  Make sure you follow the setup instructions @ https://github.com/davidjb/pass-ios#setup.

There's some rough edges, but it's functional enough for now.  Pull requests welcome!

**Comment by girst** [comment]
Thanks for the quick reply! 
I tried installing it, but it failed. 

    # dpkg -i pass.deb
    Unpacking com.davidjb.pass...
    dpkg-deb: subprocess <decompress> killed by signal (illegal instruction: 4)
    dpkg: error processing ~/pass.deb (--install):
      subprocess dpkg-deb --fsys-tarfile returned error exit status 2
    Errors were encountered while processing:
    ~/pass.deb
    # echo $?
    256

again, thanks

**Comment by davidjb** [comment]
Apparently running apt-get clean and then updating your device packages
first (e.g. via apt-get update, apt-get update) help with this sort of
issue. A web search looks like it isn't package specific. If you don't have
the APT package, search for it via Cydia and install it first (e.g. "APT
0.7 Strict").

Once you have done that, try installing again. I've installed add am
running this version on my device okay.

**Comment by girst** [comment]
yeah, it seems like something is broken in my apt, as i am getting the same error when i try to upgrade packages. 

i'll look into it. thanks for trying to help anyways

Am 01. Februar 2016 22:50:43 MEZ, schrieb David Beitey <notifications@github.com>:
>Apparently running apt-get clean and then updating your device packages
>first (e.g. via apt-get update, apt-get update) help with this sort of
>issue. A web search looks like it isn't package specific. If you don't
>have
>the APT package, search for it via Cydia and install it first (e.g.
>"APT
>0.7 Strict").
>
>Once you have done that, try installing again. I've installed add am
>running this version on my device okay.
>
>On Mon, 1 Feb 2016 at 23:30, girst <notifications@github.com> wrote:
>
>> Thanks for the quick reply!
>> I tried installing it, but it failed.
>>
>> # dpkg -i pass.deb
>> Unpacking com.davidjb.pass...
>> dpkg-deb: subprocess <decompress> killed by signal (illegal
>instruction: 4)
>> dpkg: error processing ~/pass.deb (--install):
>>   subprocess dpkg-deb --fsys-tarfile returned error exit status 2
>> Errors were encountered while processing:
>> ~/pass.deb
>> # echo $?
>> 256
>>
>> again, thanks
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/davidjb/pass-ios/issues/11#issuecomment-177972539>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/davidjb/pass-ios/issues/11#issuecomment-178211315

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by davidjb** [comment]
Try a web search on the error message, there seemed to be a few different
solutions that might work. Good luck!

**Comment by girst** [comment]
i tried most/all of them without much luck.
and it's finals week now, so i'll probably just reset my ipad next week
