### ISSUE TITLE
Publishing to Store

### ISSUE THREAD

**Issue by indigo423** [davidjb/pass-ios#13]
Just a question, are there any plans to make this application available on the Appstore?

Thank you in advance

**Comment by davidjb** [comment]
I'm certainly keen on making this happen; the current install process is cumbersome at best.  That said, it's a sizeable project with lots of pieces, and licensing will very likely require the whole thing be rewritten from scratch if it were to be available on the App Store.  Essentially, check out issue #8 -- if you're skilled in the ways of Objective-C or Swift, help is well appreciated.

**Comment by indigo423** [comment]
thank you for quick and fast reply.
